spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev  #开发环境
  application:
    name: Rubbish-service-dev
---
spring:
  profiles: test
    application:
      name: Rubbish-service-test
