spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/
spring:
  profiles: dev  #开发环境
  application:
    name: Rubbish-service-dev
---
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/
spring:
  profiles: test #测试环境
  application:
    name: Rubbish-service-test
